### ISSUE TITLE
Corregir escritura a `.gpkg`

### ISSUE THREAD

**Issue by RodrigoMahalufRecasens** [fire2a/fire-analytics-qgis-processing-toolbox-plugin#14]

**Comment by fdobad** [comment]
@RodrigoMahalufRecasens 
es un bug o feature request?
0. contexto, razonamiento o justificación
1. qué versión
2. cómo reproducir
3. qué debería suceder

**Comment by RodrigoMahalufRecasens** [comment]
Jajaja sí, lo siento. Algo me distrajo y no terminé de escribir esto. Cuando haga las simulaciones que tengo que hacer para susete, trataré de replicar el problema y lo describo major.

**Comment by fdobad** [comment]
@RodrigoMahalufRecasens please follow our [guidelines](https://fire2a.github.io/docs/docs/qgis-cookbook/README.html#getting-help-) to get help

**Comment by fdobad** [comment]
dead by author not explaining the issue
